version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 8.0
        commands:
            - echo Installing .NET 8.0
            - dotnet --version
    
    pre_build:
        commands:
            - echo Restoring dependencies
            - dotnet restore
            
    build:
        commands:
            - echo Building the .NET project
            - dotnet build -c Release
     
    post_build:
        commands: 
            - echo Running tests
            - echo Packaging the application
            - dotnet publish -c Release -o ./publish
            - ls -la
            - ls -la ./publish
            - echo Zipping the application
            - cd ./publish
            - zip -r ../lambda_function.zip .
            - cd ..
            - echo Updating Lambda function
            - aws lambda update-function-code --function-name deploy --zip-file fileb://lambda_function.zip

artifacts:
    files:
        - '**/*'
    base-directory: ./
    
cache:
    paths:
        - '/root/.nuget/packages/**/*'
