version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 8.0
        commands:
            - echo Installing .NET 8.0
            - dotnet --version
    
    pre_build:
        commands:
            - echo Restoring dependencies
            - dotnet restore
            
    build:
        commands:
            - echo Building the .NET project
            - dotnet build -c Release
     
    post_build:
        commands: 
            - echo Running tests
            - echo Test to be added to project later 
            - echo Packaging the application
            - dotnet publish -c Release -o ./publish
            - echo Zipping the application
            - cd ./publish
            - zip -r ../my_function.zip .
            - cd ..
            - echo Updating Lambda function
            - aws lambda update-function-code --function-name ${FUNCTION_NAME} --zip-file fileb://my_function.zip
